select * from [dbo].[customer_shopping_behavior (2)]

--Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue
from [dbo].[customer_shopping_behavior (2)]
group by gender

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
select customer_id,purchase_amount from[dbo].[customer_shopping_behavior (2)]
where discount_applied='Yes' and purchase_amount>(select AVG(purchase_amount) from[dbo].[customer_shopping_behavior (2)] )

-- Q3. Which are the top 5 products with the highest average review rating?
select top 5 item_purchased,avg(review_rating)[RATING] from [dbo].[customer_shopping_behavior (2)]
group by item_purchased

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping.
select shipping_type, 
ROUND(AVG(purchase_amount),2)
from [dbo].[customer_shopping_behavior (2)]
where shipping_type in ('Standard','Express')
group by shipping_type;


--Q5. Do subscribed customers spend more? Compare average spend and total revenue 
--between subscribers and non-subscribers.
select subscription_status,COUNT(customer_id) AS total_customers, avg(purchase_amount)[avg spend],sum(purchase_amount)[total revenue] from[dbo].[customer_shopping_behavior (2)] 
group by subscription_status


--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT top 5 item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2)[discount_rate]
FROM [dbo].[customer_shopping_behavior (2)]
GROUP BY item_purchased



--Q7. Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment. 
with customer_type as (
SELECT customer_id, previous_purchases,
CASE 
    WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM [dbo].[customer_shopping_behavior (2)])

select customer_segment,count(*) AS "Number of Customers" 
from customer_type 
group by customer_segment;



--Q8. What are the top 3 most purchased products within each category? 
WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM [dbo].[customer_shopping_behavior (2)]
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;



--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyers
FROM [dbo].[customer_shopping_behavior (2)]
WHERE previous_purchases > 5
GROUP BY subscription_status;

--Q10. What is the revenue contribution of each age group? 
select age_group,sum(purchase_amount)[revenue] from [dbo].[customer_shopping_behavior (2)]
group by age_group
